export const taskTypes={
    ADD_NEW_TASK:"ADD_NEW_TASK",
    REMOVE_ALL_TASKS:"REMOVE_ALL_TASKS",
    SET_SELECTED_TASK_DATA:"SET_SELECTED_TASK_DATA",
    MARK_TASK_AS_COMPLETE:"MARK_TASK_AS_COMPLETE"
}